# -*- coding: utf-8 -*-
"""controlflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlMzO6NbrngvMVfjpRtNNsvqJAUx_WoQ
"""

# Check Even or Odd
# Ask the user for a number and print whether it is even or odd.
number = int(input("Enter number :"))
if number % 2 == 0:
    print(f"{number} is EVEN")
else:
    print(f"{number} is ODD")

# Positive, Negative, or Zero
# Ask the user for a number and print whether it’s positive, negative, or zero.
number = int(input("Enter number :"))
if number > 0:
    print(f"{number} is positive")
elif number == 0:
    print(f"{number} is zero")
elif number < 0:
    print(f"{number} is negative")

# Compare Two Numbers
# Ask the user to enter two numbers and print which one is larger or if they’re equal.
number1 = int(input("Enter number 1:"))
number2 = int(input("Enter number 2 :"))
if number1 > number2:
    print(f"{number1} is greater")
elif number1 == number2:
    print(f"{number1} is equal to {number2}")
elif number1 < number2:
    print(f"{number2} is greater")

# Grading System
# Ask for a score (0–100) and print:
score = int(input("Enter score :"))
if score >= 80:
    Grade = "A"
elif score >= 60:
    Grade = "B"
elif score >= 40:
    Grade = "C"
else:
  Grade = "F"

print(f"Your Grade is {Grade}")

# Check Leap Year
# Ask for a year and check if it’s a leap year.
year = int(input("Enter a year:"))
if(year % 4 ==0) and (year % 100 != 0):
  print(f"{year} is a leap year")
else:
    print(f"{year} is not a leap year")

# Print Numbers from 1 to 10
# Use a for loop to print numbers 1 through 10.
for i in range(1,11):
  print(i)

# Sum of First N Numbers
# Ask the user for a number n and print the sum of numbers from 1 to n.
n = int(input("Enter a number :"))
# Initialize sum
total = 0
for i in range(1,n+1):
    total += i

print(f"The sum of numbers from 1 to {n} is: {total}")

# Multiplication Table
# Ask for a number and print its multiplication table up to 10.
base_number = int(input("Enter a number :"))
for i in range(1,11):
  print(f"{base_number} X {i} = {base_number * i}")

# Count Digits in a Number
# Ask the user for a number and use a while loop to count how many digits it has.
num = int(input("Enter a number: "))
count = 0
temp = abs(num)   # handle negative numbers
if temp == 0:
    count = 1
else:
    while temp > 0:
        temp //= 10   # remove the last digit
        count += 1
print(f"The number {num} has {count} digits.")

# Find Factorial (using Loop)
# Ask for a number and find its factorial using a loop.
num = int(input("Enter a number: "))
factorial = 1

if num < 0:
    print("Factorial does not exist for negative numbers.")
elif num == 0:
    print("The factorial of 0 is 1.")
else:
    for i in range(1, num + 1):
        factorial *= i
    print(f"The factorial of {num} is {factorial}.")

# Find Prime Numbers (1–50)
# Use nested loops to print all prime numbers between 1 and 50.
print("Prime numbers between 1 and 50 are:")
for num in range(2, 51):          # Outer loop: numbers from 2 to 50
    for i in range(2, num):       # Inner loop: check divisors
        if num % i == 0:          # If divisible, not prime
            break
    else:
        print(num)

# Check for Prime Number
# Ask the user for a number and check (using nested loops) if it’s prime or not.
num = int(input("Enter a number: "))
if num > 1:
    for i in range(2, num):
        if num % i == 0:
            print(f"{num} is NOT a prime number (divisible by {i}).")
            break
    else:
        print(f"{num} is a PRIME number (divisible only by 1 and itself).")
else:
    print("Number must be greater than 1.")

# List Common Elements
# Given two lists, use nested loops to print elements that appear in both lists.
# Define two lists
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
print("Common elements:")
# Nested loops to check for matches
for i in list1:
    for j in list2:
        if i == j:
            print(i)

# Find Duplicate Items
# Given a list, use nested loops to find duplicate values.
# Sample list
numbers = [2, 4, 5, 2, 3, 5, 7, 8, 3]

print("Duplicate items are:")

# Nested loops to find duplicates
for i in range(len(numbers)):
    for j in range(i + 1, len(numbers)):
        if numbers[i] == numbers[j]:
            print(numbers[i])
            break   # stop checking further duplicates for the same value

# Compare Two Strings
# Use nested loops to compare characters of two strings and print common letters.
str1 = input("Enter first string")
str2 = input("Enter second string")
for ch1 in str1:
  for ch2 in str2:
    if ch1 == ch2:
     print(f"commin characters are: {ch1}");

# Sum of List Elements
# Create a list of numbers and use a loop to find the total sum.
numbers = [2, 12, 16, 1, 5, 3]
sum = 0
for num in numbers:
  sum += num

print("The total sum is:", sum)

# Count Vowels in a Word
# Ask for a word and count the number of vowels in it.
word = input("Enter a word to count vowels in :")
vowels = "aeiouAEIOU"
count = 0

for ch in word:
  if ch in vowels:
    count += 1

print(f"The word '{word}' has {count} vowel(s).")

# Find Maximum in a List
# Find the largest number in a list without using max().
numbers = [12, 45,21,390, 455,12,2]
# assume first number is largest
largest = numbers[0]

for num in numbers:
    if num > largest:
        largest = num

print("The largest number is:", largest)

# Reverse a String
# Ask for a string and print it in reverse order.
revstr = input("Enter a string to reverse :")

rev = ""
for ch in revstr:
  rev = ch + rev

print(rev)

# Word Frequency Counter
# Ask for a sentence and use a dictionary to count how many times each word appears.
sentence = input("Enter a sentence to count: ")
# Split the sentence into words
words = sentence.split()

# Create an empty dictionary to store word counts
word_count = {}
# Loop through each word and count
for word in words:
    # Convert word to lowercase for consistent counting
    word = word.lower()
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

# Print word frequencies
print("\nWord Frequency:")
for word, count in word_count.items():
    print(f"{word}: {count}")

# 5. FUNCTIONS
# Greeting Function
# Write a function called greet() that prints a simple greeting message.
def greet():
    print("Hello Sir!")
greet();

# Sum Function
# Write a function that takes two numbers and returns their sum.
def addTwonumbers(num1, num2):
  return num1 + num2

addTwonumbers(12,3)

# Even or Odd Function
# Write a function that takes a number and returns “Even” or “Odd”.
numbering = int(input("Enter a number: "))
def checkNumber(numbering):
  if numbering % 2 == 0:
    print("The number is even")
  else:
      print("The number is odd")

checkNumber(numbering)

# Find Minimum in List Function
# Write a function that takes a list of numbers and returns the smallest one.
least_number = [12,1,23,-4,12,65,344]
small = least_number[0]

for num in least_number:
    if num < small:
        small = num

print("The smallest number is:", small)

# Count Letters Function
# Write a function that takes a string and returns how many letters it contains (ignore spaces).
def count_letters(text):
    count = 0
    for ch in text:
        if ch != " ":
            count += 1
    return count

# Ask user for input
sentence = input("Enter a string: ")

# Call the function
letters = count_letters(sentence)

print("The string contains", letters, "letters (excluding spaces).")